services:
  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: project-app
    container_name: project-app
    ports:
    - "${APP_PORT}:3000"
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
    - mysql
  mysql:
    image: mysql:8.0
    container_name: project-sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
    - "3307:3306"
    volumes:
    - project-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-app
    ports:
    - "8080:80"
    environment:
      PMA_HOST: mysql
  redis:
    image: redis
    container_name: redis-app
volumes:
  project-db: